name: Scratchip CI
language: python
script:
  - python setup.py bdist_wheel
before_deploy:
  - export FILE=$(ls dist/*.whl)
  - echo "deploying $FILE to GitHub releases"
deploy:
  - provider: pypi
    username: $PYPI_NAME
    password: $PYPI_PW
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
     api_key: $GITHUB_TOKEN
     file: $FILE
     skip_cleanup: true
     on:
       tags: true
